== Part 3: Deploying microservices with Docker

In this part, we will deploy the monolith and the microservice as connected docker containers and  implement some microservice patterns.

=== Build Docker Image of Payara Server with additional configuration

We need to enable Hazelcast in Payara Server, therefore we'll build a custom Payara Server image. The instructions to use the stock `payara/server-full` image and its Dockerfile can be found in the https://hub.docker.com/r/payara/server-full/[Docker Hub].

To see the example, checkout the branch `13_deploy_to_docker_01_simple` in both repositories.

Go into the `cargo-tracker/docker` directory and run the following command:

`docker build -t reactivems/payara-server .`

=== Running the main application in Docker

Leave the `13_deploy_to_docker_01_simple` branch checked out.

Rebuild the cargo-tracker main application with `mvn install`.

Run the application inside Docker with the following command, with PATH_TO_THE_GITHUB_REPO substituted by the path to parent folder of the cargo-tracker project:

```
docker run -p 8080:8080 -v 'PATH_TO_THE_GITHUB_REPO/cargo-tracker/target/autodeploy':/opt/payara41/deployments reactivems/payara-server bin/asadmin start-domain -v
```

Test that the application is running at the URL: http://localhost:8080/cargo-tracker/[localhost:8080/cargo-tracker]

If the application isn't running, try building the application again to deploy it.

=== Running the Pathfinder service in Docker

Run the application inside Docker with the following command, with PATH_TO_THE_GITHUB_REPO substituted by the path to parent folder of the pathfinder project:

```
docker run -p 8081:8080  -v 'PATH_TO_THE_GITHUB_REPO/pathfinder/target':/opt/payara/deployments payara/micro java -jar /opt/payara/payara-micro.jar --deploy /opt/payara/deployments/pathfinder.war
```

Test that the service is running and exposes a REST resource at the URL: http://localhost:8081/pathfinder/rest/graph-traversal/shortest-path?origin=CNHKG&destination=AUMEL

=== Running multiple Pathfinder services in Docker

Run additional services with the same docker command, but with modified port mapping. It's not necessary to map the HTTP port:

```
docker run -v 'PATH_TO_THE_GITHUB_REPO/pathfinder/target':/opt/payara/deployments payara/micro java -jar /opt/payara/payara-micro.jar --deploy /opt/payara/deployments/pathfinder.war
```