version: "3"
services:
  monolith:
    image: cargotracker/monolith
    deploy:
      replicas: 1
    ports:
      - "4848:4848"
      - "8080:8080"
    networks:
      - cargotracker
  pathfinder:
    image: cargotracker/pathfinder
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    networks:
      - cargotracker

networks:
  cargotracker:
